name: Shared Docker Build

on:
  workflow_call:
    # Inputs allow child apps to customize the build
    inputs:
      image_name:
        required: true
        type: string
      dockerfile_path:
        required: false
        type: string
        default: "./Dockerfile"
    # Secrets are passed from the child app or inherited
    # These are credentials to login to Docker Hub
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Child App Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract Metadata (Tags, Labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.image_name }}
          # Automatically tags with 'latest' and the git commit SHA
          tags: |
            # The branch + latest tag
            type=raw,value=prod-latest,enable=${{ github.ref == 'refs/heads/master' }}
            type=raw,value=dev-latest,enable=${{ github.ref == 'refs/heads/development' }}
            type=sha,format=long
            # The branch + short SHA combined
            type=raw,value=prod-{{sha}},enable=${{ github.ref == 'refs/heads/master' }}
            type=raw,value=dev-{{sha}},enable=${{ github.ref != 'refs/heads/development' }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ inputs.dockerfile_path }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          # 2026 Best Practice: Enable GitHub Actions cache to speed up builds
          cache-from: type=gha
          cache-to: type=gha,mode=max